### ISSUE TITLE
Deprecate this repo in favor of EWC one

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-auth-backend-ldap#23]
As EWC (aka StackStorm Enterprise) was OpenSourced, deprecate this community-driven repo in favor of https://github.com/StackStorm/st2-enterprise-auth-backend-ldap which is better by quality and functionality.

**Comment by m4dcoder** [comment]
There may be some use cases in the community LDAP backend that is not covered in the enterprise version. Please review and absorb those additions before deprecating/replacing this repo with the enterprise one.

**Comment by armab** [comment]
We had the deprecation message in the repo description for more than a year:
![image](https://user-images.githubusercontent.com/1533818/166247932-fd4d83af-9113-4306-831c-239e89a4fe59.png)


I think it was sufficient time to finally set the Github archive flag in the repo and make it read-only.

**Comment by rush-skills** [comment]
Yes, I meant archiving this repo, to make the deprecation complete.

**Comment by cognifloyd** [comment]
Someone needs to compare the functionality between the two versions:

> There may be some use cases in the community LDAP backend that is not covered in the enterprise version. Please review and absorb those additions before deprecating/replacing this repo with the enterprise one.

Then, once we have a list of where they differ, we can determine what features need to be ported over to the official version. If there is nothing, then we can archive this repo.

**Comment by armab** [comment]
@cognifloyd  That message was posted 2 years ago and we had no volunteers to do that work.

If someone wants to migrate the features from this repo to the official https://github.com/StackStorm/st2-enterprise-auth-backend-ldap, - they're free to do that, as it doesn't require write access to this repo and so it could be archived.
"Github archived" repo is not deleted or hidden, it just becomes read-only. Example: https://github.com/stackStorm/chef-stackstorm

I hope that'll work for everyone.
