### ISSUE TITLE
Invalid authentication backend error

### ISSUE THREAD

**Issue by silverbp** [StackStorm/st2-auth-backend-ldap#9]
When following the directions and restarting the services you get:

Mar  4 20:23:16 stackstorm gunicorn_pecan[1220]: 2017-03-04 20:23:16,960 ERROR [-] Invalid authentication backend specified: ldap

**Comment by nzlosh** [comment]
Would you mind activating the virtual environment before installing the backend?

`source /<path to stackstorm>/st2/bin/activate`

**Comment by nzlosh** [comment]
@silverbp Did this solve your problem?

**Comment by nzlosh** [comment]
@bigmstone The documentation has been updated in the readme to reflect the need to activate the virtual environment, could we close this issue please?
